baseURL = "https://staging.elysseamore.com/"
languageCode = "en-us"
title = "Elysse Amore"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
SectionPagesMenu = "main"
Paginate = 15 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-85767008-3"
enableRobotsTXT = true
enableEmoji = true
#disqusShortname = "brewingcats"
publishDir = "docs"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]
  [languages.en]
    [languages.en.params]
      description = "All the Pretty Things 💗✨"
  [languages.es]
    [languages.es.params]
      description = "Todo sobre Belleza 💗✨"

[params]
  useGenericGdpr = false
  googleAnalytics = "UA-85767008-3"
  favicon = "images/favicon.ico"
  facebook = "https://www.facebook.com/profile.php?id=100091982683287"
  twitter = ""
  instagram = "https://www.instagram.com/elysse.amore/"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  logo = "/images/logo.jpg"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/logo.png"
  recent_posts_number = 15
  #mainSections = ["software", "uncategorized", "site"]
  env = "production"
  theme_color = '255, 153, 0'
  #link_hover = '#EFFF00' # yellow
  link_hover = '#C00000' # dark red
  #link_hover = '#DE1F1F' # red
  #link_hover = '#007bff' # blue
  #link_hover = '#00802B' # green
  siteRef = "brewingcats.com"
  #fbAppId = "100091982683287"
  #fbTokenId = "cb323292940db3edd2ab47777543b4f7"
  telemetryUrl = "https://us-central1-brewingcats.cloudfunctions.net/stagingLogger"
  telemetryDataUrl = "https://media.brewingcats.com/telemetry/"
  telemetryDataBaseName = "BrewingCats"
  telemetryDataEnv = "Staging"
  #telemetryDataEnv = "Production"
  #telemetryVizId = "viz1613956602843"
  #telemetryVizPre = "Br"
  #telemetryVizName = "BrewingCats-StagingTelemetry"
  #telemetryVizView = "Analysis"
  statsUrl = "https://us-central1-brewingcats.cloudfunctions.net/stats"
  siteEnv = "staging"
  referral = "https://brewingcats.com"
  useFooterStats = "true"
  useFooterReferral = "true"
  projectId = "staging-ElysseAmore"
  siteVersion = "1.0"
